### ISSUE TITLE
commit nixops.nix?

### ISSUE THREAD

**Issue by KiaraGrouwstra** [ghuntley/dotfiles-nixos#1]
`configuration-common.nix` states:

> For configuration specific to conventional installs and Nixops installs, see ./configuration.nix and ./nixops.nix respectively.

However, `nixops.nix` appears to be missing.
Was this file accidentally omitted?
Or was this comment the result of some scaffolding thing?

**Comment by ghuntley** [comment]
Intentially omitted.
