### ISSUE TITLE
Where this configurations is locally stored?

### ISSUE THREAD

**Issue by maxdevjs** [ghuntley/dotfiles-nixos#2]
Is this cloned directly into `/etc/nixos` or somewhere else and linked?

Thank you.

**Comment by ghuntley** [comment]
As this is my home lab / laptops they are cloned directly at /etc/nixos. In production you want to clone on your build machine, build it, store the artifafts, copy the closure and then apply it. 

IE. You shouldn't be running switch on production unless you are switching via the closure that has been copied.

http://www.haskellforall.com/2018/08/nixos-in-production.html?m=1
