### ISSUE TITLE
dotfiles

### ISSUE THREAD

**Issue by maxdevjs** [ghuntley/dotfiles-nixos#3]
Is actually 

```sh
dotfiles = stringAfter [ "users" ]
    ''
      cd /home/yeahnah
    '';
```

enough? I see some very complicated configurations about `dotfiles`...

**Comment by ghuntley** [comment]
That's truely a "it depends situation". I use this to git pull https://github.com/ghuntley/dotfiles-linux and then run `stow`. Basically I don't manage my userland application configuration via nix.

**Comment by ghuntley** [comment]
The alternative way to do this is to use nix to manage application configuration and don't install as many applications in the global configuration. Instead define a per user overlay. See https://github.com/grahamc/nixos-config?files=1

**Comment by maxdevjs** [comment]
Thank you very much, makes sense. Looking in to it.
